In [ ]:
#combining 1d and 2d numpy array
import numpy as np
a1=np.array([1, 2, 3])
a2=np.array([
    [4, 5, 6],
    [7, 8, 9]
])
a1=a1.reshape(1,3)
print(a1)
res=np.concatenate((a1,a2),axis=0)
print(res)

[[1 2 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#flatten a 2d array into 1d array
import numpy as np
a2=np.array([
    [4, 5, 6],
    [7, 8, 9]
])
res=a2.flatten()
print(res)


[4 5 6 7 8 9]


In [6]:
#reverse a numpy array
import numpy as np
a1=np.array([1, 2, 3])
res=a1[::-1]
print(res)

[3 2 1]


In [17]:
#operations practice
#Maximum value
import numpy as np
a1=np.array([1, 2, 3])
res=np.max(a1)
print("Maximum value=",res)

#minimum value
res1=np.min(a1)
print("minimum value=",res1)

#no. of rows and cols
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
r=arr.shape[0]
c=arr.shape[1]
print("Rows=",r)
print("Columns=",c)

#access each element
for row in arr:
    for element in row:
        print(element)
        
        
#access specific element
print(arr[1][0])


#sum of 2d array using for loop
sum=0
for row in arr:
    for element in row:
        sum=sum+element
        
print("Sum of elements=",sum)

#Addition of arrays
a1=np.array([1, 2, 3])
a2=np.array([4, 5, 6])
print(a1+a2)

#subtraction of arrays
print(a1-a2)

#multiplication of arrays
print(a1*a2)

#Division of arrays
print(a1/a2)




Maximum value= 3
minimum value= 1
Rows= 2
Columns= 3
1
2
3
4
5
6
4
Sum of elements= 21
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [19]:
import numpy as np
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

#iterate 3d array using for loop
for i in arr:
    for j in i:
        for k in j:
            print(k)
            
#iterate 3d array using nditer
for i in np.nditer(arr):
    print(i)
    
    

1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [21]:
#Average mean median mode of two 2d arrays
import numpy as np
a1 = np.array([
    [1, 2],
    [3, 4]
])

a2 = np.array([
    [5, 2],
    [7, 8]
])
avg = (a1+a2)/2
print("Average of array",avg)

#join two arrys
arr=np.concatenate((a1.flatten(),a2.flatten()))

mean=np.mean(arr)
print("Mean=",mean)

median=np.median(arr)
print("median=",median)

values,counts=np.unique(arr,return_counts=True)
mode=values[np.argmax(counts)]
print("Mode=",mode)

Average of array [[3. 2.]
 [5. 6.]]
Mean= 4.0
median= 3.5
Mode= 2
