In [4]:
#Convert 1D Array to 2D
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a2 = a.reshape(2, 3)
print(a2)

#print array attributes
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape =", arr.shape)
print("Dimension =", arr.ndim)
print("Data Type =", arr.dtype)
rows = arr.shape[0]
cols = arr.shape[1]

print("Rows =", rows)
print("Columns =", cols)

#3×3 array of all 9
arr = np.full((3,3), 9)
print(arr)


#Create a 1D Array of 10 Evenly Spaced Values Between 25 and 125
arr = np.linspace(25, 125, 10)
print(arr)

#Convert Python List into NumPy Array
lst = [10, 20, 30, 40]
arr = np.array(lst)
print(arr)

#Reverse a 1D NumPy Array
arr = np.array([1, 2, 3, 4, 5])
rev = arr[::-1]
print(rev)

#Create a 4×4×3 Array and Extract Value at Second Set, First Row and Last Column
arr = np.arange(48).reshape(4, 4, 3)
print(arr)
print("Required Value =", arr[1, 0, 2])


#Create a 4×4 Array and Extract Odd Rows and Even Columns
arr= np.arange(1, 17).reshape(4, 4)
print(arr)
res=arr[1::2, ::2]
print(res)

#Slice First Two Rows and First Two Columns of Second Set from a 4×4×3 Array
arr=np.arange(48).reshape(4, 4, 3)
res=arr[1, :2, :2]
print(res)

#Replace All Odd Numbers with -1 Using For Loop
arr = np.array([[3,5,8,9],
                [1,8,3,2]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1

print(arr)

#Get Indices of Non-Zero Elements
arr=np.array([1, 0, 2, 0, 3, 0, 4])
ind=np.nonzero(arr)
print(ind)

# Arithmetic operations element-wise
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
print("add",arr1+arr2)
print("mul",arr1*arr2)

#Compute Dot Product
res=np.dot(arr1, arr2)
print(res)





[[1 2 3]
 [4 5 6]]
Shape = (2, 3)
Dimension = 2
Data Type = int64
Rows = 2
Columns = 3
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]
[10 20 30 40]
[5 4 3 2 1]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
Required Value = 14
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 5  7]
 [13 15]]
[[12 13]
 [15 16]]
[[-1 -1  8 -1]
 [-1  8 -1  2]]
(array([0, 2, 4, 6]),)
add [11 22 33]
mul [10 40 90]
140
